-- This module serves as the root of the `UCLMATH0109` library.
-- Import modules here that should be built as part of the library.
import «UCLMATH0109».Course._1_intro.example_limits
import «UCLMATH0109».Course._2_foundations.A_functions
import «UCLMATH0109».Course._2_foundations.B_or_and_imp
import «UCLMATH0109».Course._2_foundations.C_not_false
import «UCLMATH0109».Course._2_foundations.D_quantifiers
import «UCLMATH0109».Course._2_foundations.E_equality_rfl_rw
import «UCLMATH0109».Course._2_foundations.F_nat
import «UCLMATH0109».Course._2_foundations.G_ext
import «UCLMATH0109».Course._2_foundations.H_Mathlib
import «UCLMATH0109».Course._2_foundations.sheet2A
import «UCLMATH0109».Course._2_foundations.sheet2B
import «UCLMATH0109».Course._2_foundations.sheet2C
import «UCLMATH0109».Course._2_foundations.sheet2D
import «UCLMATH0109».Course._2_foundations.sheet2E
import «UCLMATH0109».Course._2_foundations.sheet2F
import «UCLMATH0109».Course._2_foundations.sheet2G
import «UCLMATH0109».Course._2_foundations.sheet2H
import «UCLMATH0109».Course._3_analysis_playground.A_structured_tactics
import «UCLMATH0109».Course._3_analysis_playground.B_higher_tactics
import «UCLMATH0109».Course._3_analysis_playground.C_have
import «UCLMATH0109».Course._3_analysis_playground.D_calc
import «UCLMATH0109».Course._3_analysis_playground.E1_intro_to_finsets
import «UCLMATH0109».Course._3_analysis_playground.E2_let
import «UCLMATH0109».Course._3_analysis_playground.F_casts
--import «UCLMATH0109».Course._3_analysis_playground.sheet3A
import «UCLMATH0109».Course._3_analysis_playground.sheet3B
--import «UCLMATH0109».Course._3_analysis_playground.sheet3C
import «UCLMATH0109».Course._3_analysis_playground.sheet3D
--import «UCLMATH0109».Course._3_analysis_playground.sheet3E
--import «UCLMATH0109».Course._3_analysis_playground.sheet3F
import «UCLMATH0109».Course._4_structures_and_classes.A_structures_and_classes
import «UCLMATH0109».Course._4_structures_and_classes.B_defining_a_class
import «UCLMATH0109».Course._4_structures_and_classes.C_groups
import «UCLMATH0109».Course._4_structures_and_classes.D_simp
import «UCLMATH0109».Course._4_structures_and_classes.sheet4A
import «UCLMATH0109».Course._4_structures_and_classes.sheet4B
import «UCLMATH0109».Course._4_structures_and_classes.sheet4C
import «UCLMATH0109».Course._4_structures_and_classes.sheet4D
