import Mathlib.Tactic

/-!
Define the ring `D` whose elements have the form
`a+b*dx`, where `x` and `y` are real numbers, and `dx^2 = 0`.

Create a instances of `CommRing D` and `Module ℝ D` These say that `D` is a
commutative ring, and also a vector space over `ℝ`.

Show that a+b*dx is invertible iff a ≠ 0, and create an instance of `Inv D`.

Find out what an algebra is and create an instance of `Algebra ℝ D`.
Define an ordering on your ring so that dx is positive, but smaller than every
positive real number. Find out what an ordered ring is and create an
instance of this for `D`.

Prove that for any `f : ℝ[X]` and any `c : ℝ` we have $f(c + dx) = f(c) + f'(c) dx$.
-/

@[ext]
structure D where
  a : ℝ
  b : ℝ

namespace D

def dx : D := ⟨0,1⟩

def one : D := ⟨1,0⟩

def zero : D := ⟨0,0⟩

/-
define addition, multiplication and negation of dual numbers.
-/
def add (r s : D) : D := sorry

def mul (r s : D) : D := sorry

def neg (r : D) : D := sorry

instance : Add D := ⟨add⟩
instance : Mul D := ⟨mul⟩
instance : Zero D := ⟨zero⟩
instance : One D := ⟨one⟩
instance : Neg D := ⟨neg⟩

/-
state and prove a definitional lemma for negation.
-/
lemma neg_def (r : D) : -r = sorry := sorry

/-
make definitional lemmas for the other definitions above.
-/

instance : CommRing D := sorry

/-
define scalar multiplicatio of dual numbers by real numbers.
-/
def smul (r : ℝ) (s : D) : D := sorry

/-
Prove that the Dual numbers form a vector space over the real numbers.
-/
instance : Module ℝ D := sorry

-- make a definitional lemma for `smul`.

/-
Define the inverse of a dual number.
This should default to `0` if the dual number isn't invertible.
-/
def inv (r : D) : D := sorry

instance : Inv D := ⟨inv⟩

lemma inv_mul_self (r : D) (h : r.a ≠ 0) : r⁻¹ * r = 1 :=
by
  sorry

lemma mul_inv_self (r : D) (h : r.a ≠ 0) : r * r⁻¹ = 1 :=
by
  sorry

lemma invertible_iff (r : D) : r.a ≠ 0 ↔ ∃ s : D, r * s = 1 :=
by
  sorry

/-
Show that the dual numbers form an algebra over `ℝ`.
(an algebra over `ℝ` is both a ring and a vector space, with a fw other axioms.)
-/
instance : Algebra ℝ D := sorry

/-
Define an ordering on the set of dual numbers.
You should do this in such a way that `a + b * dx ≤ a' + b' * dx` if and only
if `a < a'` or `a=a'` and `b ≤ b'`.
-/
def le (r s : D) : Prop := sorry

-- add a definitional lemma for `r ≤ s`

/-
Prove that the dual numbers form an "ordered ring".
-/
instance : OrderedRing D where
  le := le
  le_refl := sorry
  le_trans := sorry
  le_antisymm := sorry
  add_le_add_left := sorry
  zero_le_one := sorry
  mul_nonneg := sorry

/-
Define a coercion from `ℝ` ro `D`,
sending the real number `x` to `x + 0 * dx`.
-/
instance : Coe ℝ D where
  coe x := sorry

/-
Prove that `dx` is smaller than every positive real number.
-/
example : ∀ x : ℝ, 0 < x → dx < x :=
by
  sorry

example (r : D) (r' : ℝ) (h₁ : r' < r) (h₂ : ∀ ε : ℝ, 0 < ε → r < r' + ε) :
  ∃ s : ℝ, s > 0 ∧ r = r' + s * dx :=
by
  sorry

open Polynomial

/-
prove that f(x + dx) = f(x) + f'(x) dx, where f is a polynomial and x is a real number.
-/
theorem aeval (f : ℝ[X]) (x : ℝ) :
    aeval ( x + dx ) f = aeval x f + (aeval x (derivative f)) * dx :=
by
  sorry

/-
# Ideas for extra topics that you could try

Show that `D` has exactly three ideals. They are the principal
ideals generated by `0`, `dx` and `1`.

Define an "absolute value" on `D` which
takes `a` to `±a`, depending on whether `a≥0`. Then generalize some
standard facts about absolute values of real numbers to the ring `D`.

Construct for every non-zero real number `c` a ring automorphism `σ c` of `D`
(i.e. an element of `D ≃+* D`), given by the formula `x+y*dx ↦ x+c*y*dx`.

Construct `σ c` an an `ℝ`-algebra homomorphism (i.e. an element of `D ≃ₐ[ℝ] D`).
This amounts to proving that (as well as being a ring homomorphism) it is
also a linear map. Then you can try proving that `σ` is a group isomorphism
between `ℝˣ` and `D ≃ₐ[ℝ] D`. In other words, redefine `σ` as an element of
`ℝˣ ≃* (D ≃ₐ[ℝ] D)`.

Let `F` be any field. Show that if we have a ring homomorphism
`φ : F →+* D`, then the image of `φ` is contained in the subring of real
numbers in `D`. Show that if `φ : D →+* F` then `φ dx = 0`, and in fact
the kernel of `φ` is equal to the ideal of all multiples of `dx`.
Construct equivalences `(F →+* D) ≃ (F →+* ℝ)` and
`(D →+* F) ≃ (ℝ →+* F)`.
-/
